### ISSUE TITLE
addresses_from_mnemonic.py error

### ISSUE THREAD

**Issue by timmolter** [cryptobi/avax-python#2]
When I run ` python3 offline/wallet/addresses_from_mnemonic.py shoulder man day worry sweet clip outdoor little matter interest option eyebrow asset visa snake find toddler labor puzzle danger quit secret flip foil`, I get the following error:

```
Traceback (most recent call last):
  File "~/Documents/gitlab/avax-python/offline/wallet/addresses_from_mnemonic.py", line 31, in <module>
    from avaxpython.wallet import generator, BIP32
ModuleNotFoundError: No module named 'avaxpython'
```

Are you sure the setup steps in the readme are correct? I'm not too familiar with Python...

**Comment by ojrdevcom** [comment]
Did you run `. setenv.sh` in the directory where you cloned `avax-python` before running your script?

**Comment by timmolter** [comment]
yes, I did, but that gave me an error. I'll try to repeat it and post here again.

**Comment by timmolter** [comment]
It turns out I had to run it like: `. ./setenv.sh`. Now onto the next error...
